In [1]:
import pandas as pd
import os
from dotenv import load_dotenv
db_pwd = os.getenv('mysqlpwd')

In [2]:
df = pd.DataFrame({"age":[20,22,18,10],"name":['niko','zzz','nox','ze'],"id":[101,102,103,104]})
df.set_index("id",inplace=True) #tips:让id作为列索引
df

     age  name
id
101   20  niko
102   22   zzz
103   18   nox
104   10    ze

In [4]:
from sqlalchemy import create_engine
engine=create_engine(
    f"mysql+pymysql://root:{db_pwd}@localhost:3306/df2sql"
)

In [5]:
df.to_sql(
    name="demo2sql",
    con=engine,
    if_exists="replace",
    index=False, #tips:不将DataFrame的索引写入数据库
    chunksize=1000,#tips:批量插入的大小,对于大数据集很有用
)
print('数据成功导出到数据库')

数据成功导出到数据库

## 拿到数据库中的数据

In [6]:
df2 = pd.read_sql(
    "select * from demo2sql",
    con=engine
)
df2

   age  name
0   20  niko
1   22   zzz
2   18   nox
3   10    ze

In [7]:
type(df2)

pandas.core.frame.DataFrame