In [1]:
import pandas  as pd

In [2]:
df = pd.DataFrame({'gmv':[100,200,300,400],'trade_date':["2025-01-06","2023-10-31","2023-12-31","2023-01-05"]})
df

   gmv  trade_date
0  100  2025-01-06
1  200  2023-10-31
2  300  2023-12-31
3  400  2023-01-05

In [8]:
df['ymd']=pd.to_datetime(df['trade_date'])

In [9]:
df

   gmv  trade_date        ymd
0  100  2025-01-06 2025-01-06
1  200  2023-10-31 2023-10-31
2  300  2023-12-31 2023-12-31
3  400  2023-01-05 2023-01-05

In [10]:
df.dtypes

gmv                    int64
trade_date            object
ymd           datetime64[ns]
dtype: object

**dt是时间属性访问器对象**

In [12]:
df["year"]=df["ymd"].dt.year
df

   gmv  trade_date        ymd  year
0  100  2025-01-06 2025-01-06  2025
1  200  2023-10-31 2023-10-31  2023
2  300  2023-12-31 2023-12-31  2023
3  400  2023-01-05 2023-01-05  2023

In [13]:
df["ymd"].dt.month

0     1
1    10
2    12
3     1
Name: ymd, dtype: int32

In [14]:
df["ymd"].dt.day

0     6
1    31
2    31
3     5
Name: ymd, dtype: int32

In [15]:
df["ymd"].dt.dayofweek

0    0
1    1
2    6
3    3
Name: ymd, dtype: int32

In [16]:
df['ymd'].dt.quarter #tips:查看季度

0    1
1    4
2    4
3    1
Name: ymd, dtype: int32

In [17]:
df["ymd"].dt.is_month_end #tips:看看是不是月底

0    False
1     True
2     True
3    False
Name: ymd, dtype: bool

In [18]:
df["ymd"].dt.is_year_end #tips:看看是不是年底

0    False
1    False
2     True
3    False
Name: ymd, dtype: bool

In [21]:
df['ystat']=df['ymd'].dt.to_period("Y") #按年统计
df['mstat']=df['ymd'].dt.to_period('M') #按月统计
df['qstat']=df['ymd'].dt.to_period('Q') #按季度统计
df['wstat']=df['ymd'].dt.to_period('W') #按周统计

In [22]:
df

,gmv,trade_date,ymd,year,ystat,mstat,qstat,wstat
0,100,2025-01-06,2025-01-06,2025,2025,2025-01,2025Q1,2025-01-06/2025-01-12
1,200,2023-10-31,2023-10-31,2023,2023,2023-10,2023Q4,2023-10-30/2023-11-05
2,300,2023-12-31,2023-12-31,2023,2023,2023-12,2023Q4,2023-12-25/2023-12-31
3,400,2023-01-05,2023-01-05,2023,2023,2023-01,2023Q1,2023-01-02/2023-01-08