In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv('./datas/weather.csv')
df.describe()

       precipitation     temp_max     temp_min         wind
count    1461.000000  1461.000000  1461.000000  1461.000000
mean        3.029432    16.439083     8.234771     3.241136
std         6.680194     7.349758     5.023004     1.437825
min         0.000000    -1.600000    -7.100000     0.400000
25%         0.000000    10.600000     4.400000     2.200000
50%         0.000000    15.600000     8.300000     3.000000
75%         2.800000    22.200000    12.200000     4.000000
max        55.900000    35.600000    18.300000     9.500000

In [3]:
df.head(5)

         date  precipitation  temp_max  temp_min  wind  weather
0  2012-01-01            0.0      12.8       5.0   4.7  drizzle
1  2012-01-02           10.9      10.6       2.8   4.5     rain
2  2012-01-03            0.8      11.7       7.2   2.3     rain
3  2012-01-04           20.3      12.2       5.6   4.7     rain
4  2012-01-05            1.3       8.9       2.8   6.1     rain

In [4]:
df.columns

Index(['date', 'precipitation', 'temp_max', 'temp_min', 'wind', 'weather'], dtype='str')

In [5]:
df.shape

(1461, 6)

In [6]:
df.dtypes

date                 str
precipitation    float64
temp_max         float64
temp_min         float64
wind             float64
weather              str
dtype: object

In [7]:
df.isna().sum()

date             0
precipitation    0
temp_max         0
temp_min         0
wind             0
weather          0
dtype: int64

日期列还是需要转化为日期类型的,因为它现在还是object

dt 是时间属性访问器对象

In [8]:
df['month']=pd.to_datetime(df['date']).dt.to_period('M').astype(str) #tips:按月进行统计

In [9]:
df

            date  precipitation  temp_max  temp_min  wind  weather    month
0     2012-01-01            0.0      12.8       5.0   4.7  drizzle  2012-01
1     2012-01-02           10.9      10.6       2.8   4.5     rain  2012-01
2     2012-01-03            0.8      11.7       7.2   2.3     rain  2012-01
3     2012-01-04           20.3      12.2       5.6   4.7     rain  2012-01
4     2012-01-05            1.3       8.9       2.8   6.1     rain  2012-01
...          ...            ...       ...       ...   ...      ...      ...
1456  2015-12-27            8.6       4.4       1.7   2.9     rain  2015-12
1457  2015-12-28            1.5       5.0       1.7   1.3     rain  2015-12
1458  2015-12-29            0.0       7.2       0.6   2.6      fog  2015-12
1459  2015-12-30            0.0       5.6      -1.0   3.4      sun  2015-12
1460  2015-12-31            0.0       5.6      -2.1   3.5      sun  2015-12

[1461 rows x 7 columns]

## 分组聚合

```python
df.groupby('分组字段')["要聚合的的字段"].聚合函数()
df.groupby(['分组字段1','分组字段2',...])[["要聚合的字段1","要聚合的字段2"]].聚合函数()
```

In [10]:
df.groupby('month')[["temp_max","temp_min"]].mean() #important:按月分组

#tips:按照sql理解 select AVG(temp_max),AVG(temp_min) from df groupby month;

          temp_max   temp_min
month
2012-01   7.054839   1.541935
2012-02   9.275862   3.203448
2012-03   9.554839   2.838710
2012-04  14.873333   5.993333
2012-05  17.661290   8.190323
2012-06  18.693333  10.480000
2012-07  22.906452  12.932258
2012-08  25.858065  14.009677
2012-09  22.880000  11.243333
2012-10  15.829032   8.380645
2012-11  11.326667   5.226667
2012-12   7.235484   3.293548
2013-01   6.106452   0.796774
2013-02   9.467857   4.325000
2013-03  12.709677   4.977419
2013-04  14.243333   6.696667
2013-05  19.625806   9.922581
2013-06  23.253333  13.163333
2013-07  26.093548  13.932258
2013-08  26.119355  15.480645
2013-09  21.360000  13.590000
2013-10  14.229032   7.638710
2013-11  12.053333   5.590000
2013-12   7.022581   1.570968
2014-01   9.600000   4.096774
2014-02   8.200000   2.635714
2014-03  12.906452   5.425806
2014-04  15.460000   6.730000
2014-05  19.870968  10.216129
2014-06  21.590000  11.756667
2014-07  26.900000  14.425806
2014-08  26.383871  14.893548
2014-09  23.163333  13.233333
2014-10  17.961290  10.883871
2014-11  11.030000   4.510000
2014-12  10.138710   4.609677
2015-01  10.154839   4.351613
2015-02  12.517857   6.085714
2015-03  14.377419   6.193548
2015-04  15.503333   6.030000
2015-05  20.025806  10.129032
2015-06  26.063333  13.576667
2015-07  28.093548  15.500000
2015-08  26.087097  14.693548
2015-09  20.293333  11.366667
2015-10  17.538710  10.500000
2015-11   9.683333   3.480000
2015-12   8.380645   3.825806

In [11]:
#important:统计每个月不同天气状况的数量

df.groupby('month')['weather'].nunique()

#tips:SELECT COUNT(DISTINCT weather) FROM df GROUP BY month;

month
2012-01    4
2012-02    4
2012-03    4
2012-04    4
2012-05    3
2012-06    3
2012-07    4
2012-08    3
2012-09    4
2012-10    3
2012-11    4
2012-12    4
2013-01    4
2013-02    3
2013-03    5
2013-04    4
2013-05    3
2013-06    2
2013-07    2
2013-08    3
2013-09    3
2013-10    3
2013-11    4
2013-12    3
2014-01    3
2014-02    3
2014-03    3
2014-04    2
2014-05    2
2014-06    2
2014-07    3
2014-08    3
2014-09    3
2014-10    3
2014-11    4
2014-12    3
2015-01    3
2015-02    3
2015-03    3
2015-04    3
2015-05    3
2015-06    4
2015-07    4
2015-08    4
2015-09    3
2015-10    4
2015-11    3
2015-12    3
Name: weather, dtype: int64

In [12]:
df.describe(include='all') #tips:一般不用all

,date,precipitation,temp_max,temp_min,wind,weather,month
count,1461,1461.000000,1461.000000,1461.000000,1461.000000,1461,1461
unique,1461,NaN,NaN,NaN,NaN,5,48
top,2012-01-01,NaN,NaN,NaN,NaN,rain,2012-01
freq,1,NaN,NaN,NaN,NaN,641,31
mean,NaN,3.029432,16.439083,8.234771,3.241136,NaN,NaN
std,NaN,6.680194,7.349758,5.023004,1.437825,NaN,NaN
min,NaN,0.000000,-1.600000,-7.100000,0.400000,NaN,NaN
25%,NaN,0.000000,10.600000,4.400000,2.200000,NaN,NaN
50%,NaN,0.000000,15.600000,8.300000,3.000000,NaN,NaN
75%,NaN,2.800000,22.200000,12.200000,4.000000,NaN,NaN
max,NaN,55.900000,35.600000,18.300000,9.500000,NaN,NaN

In [13]:
df.describe(include=np.float64)

       precipitation     temp_max     temp_min         wind
count    1461.000000  1461.000000  1461.000000  1461.000000
mean        3.029432    16.439083     8.234771     3.241136
std         6.680194     7.349758     5.023004     1.437825
min         0.000000    -1.600000    -7.100000     0.400000
25%         0.000000    10.600000     4.400000     2.200000
50%         0.000000    15.600000     8.300000     3.000000
75%         2.800000    22.200000    12.200000     4.000000
max        55.900000    35.600000    18.300000     9.500000

In [14]:
df[['temp_max','temp_min']].describe(include=np.float64).T

           count       mean       std  min   25%   50%   75%   max
temp_max  1461.0  16.439083  7.349758 -1.6  10.6  15.6  22.2  35.6
temp_min  1461.0   8.234771  5.023004 -7.1   4.4   8.3  12.2  18.3

## 常用排序方法

```python
def nlargest(
        self, n: int, columns: IndexLabel, keep: NsmallestNlargestKeep = "first"
    ) -> DataFrame:
  pass

```

In [15]:
df.nlargest(3,'temp_max') #tips:查看最高温度排名前三的

            date  precipitation  temp_max  temp_min  wind weather    month
953   2014-08-11            0.5      35.6      17.8   2.6    rain  2014-08
1295  2015-07-19            0.0      35.0      17.2   3.3     sun  2015-07
228   2012-08-16            0.0      34.4      18.3   2.8     sun  2012-08

In [16]:
df.nsmallest(3,'temp_min') #tips:查看最低温度排名前三的

           date  precipitation  temp_max  temp_min  wind weather    month
706  2013-12-07            0.0       0.0      -7.1   3.1     sun  2013-12
707  2013-12-08            0.0       2.2      -6.6   2.2     sun  2013-12
767  2014-02-06            0.0      -1.6      -6.0   4.5     sun  2014-02

查看每年最高温度的几种方式

In [19]:
df['year_highest_temp']=pd.to_datetime(df['date']).dt.year
df.groupby('year_highest_temp')['temp_max'].max()

year_highest_temp
2012    34.4
2013    33.9
2014    35.6
2015    35.0
Name: temp_max, dtype: float64

In [ ]:
year_sort = df.sort_values(by=['year','temp_max'],ascending=[True,False])
year_sort.drop_duplicates(subset=['year'])