In [1]:
import pandas as pd

In [2]:
df=pd.DataFrame({"姓名":['Alice','Bob','Charlie'],"年龄":[25,30,35]})
df

        姓名  年龄
0    Alice  25
1      Bob  30
2  Charlie  35

In [3]:
#tips:获取平均年龄
df['年龄']

0    25
1    30
2    35
Name: 年龄, dtype: int64

In [5]:
df['年龄'].mean()

np.float64(30.0)

In [6]:
df2 = pd.DataFrame({'Fruit':['Apple','Banana','Apple','Banana'],'Price':[2,1,3,1.5],'Quantity':[5,8,3,6]})
df2

    Fruit  Price  Quantity
0   Apple    2.0         5
1  Banana    1.0         8
2   Apple    3.0         3
3  Banana    1.5         6

In [19]:
#使用groupby按照Fruit分组,计算每种水果的总销售额(销售额=价格*数量)

df2['Price']

0    2.0
1    1.0
2    3.0
3    1.5
Name: Price, dtype: float64

In [20]:
df2['Quantity']

0    5
1    8
2    3
3    6
Name: Quantity, dtype: int64

In [21]:
df2['total']=df2['Price']*df2['Quantity']
df2

    Fruit  Price  Quantity  total
0   Apple    2.0         5   10.0
1  Banana    1.0         8    8.0
2   Apple    3.0         3    9.0
3  Banana    1.5         6    9.0

In [22]:
df2.groupby('Fruit')['total'].sum()

Fruit
Apple     19.0
Banana    17.0
Name: total, dtype: float64