In [1]:
import pandas as pd

## concat连接

In [2]:
s1=pd.Series(index=["A","B"],data=[1,2])
s2=pd.Series(index=["D","E"],data=[1,2])
s3=pd.Series(index=["G","H"],data=[1,2])
pd.concat([s1,s2,s3],axis=0) #按照行连接，行的方向是垂直的,所以是一条向下扩展的

A    1
B    2
D    1
E    2
G    1
H    2
dtype: int64

In [3]:
pd.concat([s1,s2,s3],axis=1) #按列连接，不同列的方向是水平的,所以是一条向右的竖线

     0    1    2
A  1.0  NaN  NaN
B  2.0  NaN  NaN
D  NaN  1.0  NaN
E  NaN  2.0  NaN
G  NaN  NaN  1.0
H  NaN  NaN  2.0

## DataFrame和Serise连接

In [4]:
df1 = pd.DataFrame(data={"a": [1, 2], "b": [4, 5]}, index=[1, 2])
s1 = pd.Series(data=[7, 10], index=[1, 2], name="a")

In [5]:
df1

   a  b
1  1  4
2  2  5

In [6]:
s1

1     7
2    10
Name: a, dtype: int64

In [7]:
pd.concat([df1,s1]) #tips:默认按行连接，就是一行下面跟着一行,如果维度不匹配则填充Nan

    a    b
1   1  4.0
2   2  5.0
1   7  NaN
2  10  NaN

In [8]:
pd.concat([df1,s1],axis=1) #按照列连接

   a  b   a
1  1  4   7
2  2  5  10

## dataframe与dataframe的连接

In [9]:
df1 = pd.DataFrame(data={"a": [1, 2], "b": [4, 5]}, index=[1, 2])
df2 = pd.DataFrame(data={"a": [7, 8], "b": [10, 11]}, index=[1, 2])

In [10]:
pd.concat([df1,df2],axis=0)

   a   b
1  1   4
2  2   5
1  7  10
2  8  11

In [11]:
pd.concat([df1,df2],axis=1)

   a  b  a   b
1  1  4  7  10
2  2  5  8  11

## 重置索引

可通过ignore_index=True来重置索引。
重置索引之后索引会重新计算,而抛弃原来的索引

In [12]:
df1 = pd.DataFrame(data={"a": [1, 2], "b": [4, 5]}, index=[1, 2])
df2 = pd.DataFrame(data={"a": [7, 8], "b": [10, 11]}, index=[1, 2])

In [13]:
pd.concat([df1,df2],axis=0,ignore_index=True)

   a   b
0  1   4
1  2   5
2  7  10
3  8  11

## 类似join的连接

默认的合并方式是对其他轴进行并集合并（join=outer），可以用join=inner实现其他轴上的交集合并。

In [14]:
df1 = pd.DataFrame(data={"a": [1, 2], "b": [4, 5]}, index=[1, 2])
df2 = pd.DataFrame(data={"b": [7, 8], "c": [10, 11]}, index=[2, 3])

In [17]:
pd.concat([df1, df2],join="outer") #tips:join默认就是outer,也就是类似于sql中的全外连接

     a  b     c
1  1.0  4   NaN
2  2.0  5   NaN
2  NaN  7  10.0
3  NaN  8  11.0

In [18]:
pd.concat([df1,df2],join="inner") #tips:这样就实现了类似于sql的内连接操作

   b
1  4
2  5
2  7
3  8