apply()函数可以对DataFrame或Series的数据进行逐行、逐列或逐元素的操作。可以使用自定义函数对数据进行变换、计算或处理，通常用于处理复杂的变换逻辑，或者处理不能通过向量化操作轻松完成的任务。

3.8.1Series使用apply()

In [1]:
import pandas as pd

In [2]:
# Series的apply方法调用的函数，参数接收的是Series中的一个元素
def func(item):
    return item*20

s = pd.Series([10,20,30])

s.apply(func)

0    200
1    400
2    600
dtype: int64

也可以传入lambda表达式。

In [3]:
s.apply(lambda item:item*20)

0    200
1    400
2    600
dtype: int64

传入带参数的函数。
apply()方法会将自己没有匹配上的参数，在调用func的时候作为func的参数传递过去,必须通过关键字传参

In [4]:
def func1(item,p1):
    return item*p1

s.apply(func1,p1=3)

0    30
1    60
2    90
dtype: int64

DataFrame使用apply()

In [5]:
# DataFrame的apply方法调用的函数，参数接收的是DataFrame中的一个Series
def func(s):
    return s.sum()

df = pd.DataFrame({"a": [10, 20, 30], "b": [40, 50, 60]})

In [6]:
df

    a   b
0  10  40
1  20  50
2  30  60

In [7]:
df.apply(func)#tips:默认axis=0，按行方向进行操作，对列进行统计；

a     60
b    150
dtype: int64

In [8]:
df.apply(sum,axis=1) #tips:可以设置axis=1，按照列的方向进行操作，对行进行统计

0    50
1    70
2    90
dtype: int64

注意：df.apply一次只能处理一个Series（当axis=0时处理列，当axis=1时处理行），<br>
但如下的函数func中，获取同一个Series对象的两列数据a和b，所以不能直接使用df.apply(f)按列处理了，需要指定axis=1,按行处理，才能获取一行中的不同列。

In [10]:
def func(s):
   return s["a"] / s["b"]

df = pd.DataFrame({"a": [10, 20, 30], "b": [40, 50, 60]})

In [11]:
df

    a   b
0  10  40
1  20  50
2  30  60

In [12]:
df.apply(func,axis=1) #tips:指定按照列的方向操作每行数据,相当于10/40,20/50,30/60

0    0.25
1    0.40
2    0.50
dtype: float64