In [1]:
from idlelib.replace import replace

import pandas as pd

In [2]:
s1 = pd.DataFrame({"age":[20,30,40,10],"name":['niko','lucy','jimi','keven'],"id":[1,2,3,4]})
s1

   age   name  id
0   20   niko   1
1   30   lucy   2
2   40   jimi   3
3   10  keven   4

In [4]:
s1.set_index('id') #tips:指定行索引,返回一个新的对象

    age   name
id
1    20   niko
2    30   lucy
3    40   jimi
4    10  keven

In [5]:
s1.columns

Index(['age', 'name', 'id'], dtype='object')

In [7]:
s1.set_index('id',inplace=True) #tips:inplace是原地修改,也就是对原来的df对象直接进行修改而不是返回新的df对象

In [8]:
s1 #tips

    age   name
id
1    20   niko
2    30   lucy
3    40   jimi
4    10  keven

In [9]:
#tips:如果后悔了怎么办?
s1.reset_index(inplace=True) #tips:只要充值索引就可以了!!!

In [10]:
s1

   id  age   name
0   1   20   niko
1   2   30   lucy
2   3   40   jimi
3   4   10  keven

In [11]:
s1

   id  age   name
0   1   20   niko
1   2   30   lucy
2   3   40   jimi
3   4   10  keven

In [9]:
s1.rename(index={1:'1st',2:'2nd',3:'3rd'},inplace=True) #tips:修改行索引

In [10]:
s1

     年龄     名称  id
0    20   niko   1
1st  30   lucy   2
2nd  40   jimi   3
3rd  10  keven   4

In [7]:
s1.rename(columns={'age':'年龄','name':'名称'},inplace=True) #tips:修改列名

In [8]:
s1

   年龄     名称  id
0  20   niko   1
1  30   lucy   2
2  40   jimi   3
3  10  keven   4

In [11]:
s1.index

Index([0, '1st', '2nd', '3rd'], dtype='object')

In [12]:
s1.columns

Index(['年龄', '名称', 'id'], dtype='object')

In [14]:
s1.index.size

4

In [13]:
s1.columns.size

3

In [15]:
s1.index=['Ⅰ','Ⅱ','Ⅲ','Ⅳ','Ⅴ','Ⅵ','Ⅶ'][0:s1.index.size]

In [16]:
s1

   年龄     名称  id
Ⅰ  20   niko   1
Ⅱ  30   lucy   2
Ⅲ  40   jimi   3
Ⅳ  10  keven   4

In [17]:
s1.columns=['$','¥','฿','₫','₩','֏'][0:s1.columns.size]

In [18]:
s1

    $      ¥  ฿
Ⅰ  20   niko  1
Ⅱ  30   lucy  2
Ⅲ  40   jimi  3
Ⅳ  10  keven  4

In [20]:
s1.reset_index(inplace=True)

In [21]:
s1

  index   $      ¥  ฿
0     Ⅰ  20   niko  1
1     Ⅱ  30   lucy  2
2     Ⅲ  40   jimi  3
3     Ⅳ  10  keven  4

In [22]:
s1.columns=['index','age','name','id']
s1

  index  age   name  id
0     Ⅰ   20   niko   1
1     Ⅱ   30   lucy   2
2     Ⅲ   40   jimi   3
3     Ⅳ   10  keven   4

In [26]:
s1.columns

Index(['index', 'age', 'name', 'id'], dtype='object')

In [28]:
s1.drop("index",axis=1,inplace=True)

In [29]:
s1

   age   name  id
0   20   niko   1
1   30   lucy   2
2   40   jimi   3
3   10  keven   4

In [31]:
s2 = pd.Series({'a':1,'b':2,'c':3},name="id")
s2

a    1
b    2
c    3
Name: id, dtype: int64

In [33]:
df1 = pd.DataFrame({'id':[1,2,3],'name':['zeg','zeztz','nox']})
df1.set_index('id',inplace=True)
df1

     name
id
1     zeg
2   zeztz
3     nox

In [37]:
df1.drop(1,inplace=True)
df1

     name
id
2   zeztz
3     nox

In [42]:
df1.insert(1,"age",[20,33])
df1

     name  age
id
2   zeztz   20
3     nox   33

In [44]:
df1.iloc[0]

name    zeztz
age        20
Name: 2, dtype: object

In [45]:
df1.iloc[1]

name    nox
age      33
Name: 3, dtype: object

In [46]:
df1.index

Index([2, 3], dtype='int64', name='id')

In [47]:
df1.columns

Index(['name', 'age'], dtype='object')