In [1]:
import pandas as pd

In [2]:
import os

In [3]:
df = pd.DataFrame({"age":[20,22,18,10],"name":['niko','zzz','nox','ze'],"id":[101,102,103,104]})
df.set_index("id",inplace=True) #tips:让id作为列索引
df

     age  name
id
101   20  niko
102   22   zzz
103   18   nox
104   10    ze

In [7]:
df.to_csv('./datas/demo.csv',encoding="gbk") #tips:如果想用excel这样的软件打开的话需要指定编码为gbk编码
df.to_json('./datas/demo.json',force_ascii=False) #tips:默认导出的是ascii,如果想要友好观察那就设置为force_ascii=False

In [4]:
df.to_clipboard() #tips:导出到剪切板

再从中读取

In [8]:
df2 = pd.read_csv('./datas/demo.csv',encoding="gbk")
df2

    id  age  name
0  101   20  niko
1  102   22   zzz
2  103   18   nox
3  104   10    ze

In [9]:
df3 = pd.read_json('./datas/demo.json')
df3

     age  name
101   20  niko
102   22   zzz
103   18   nox
104   10    ze